export const content1 = {
  title: "1.  Syarat & Ketentuan Tentang Privasi",
  description1: "Kami menghargai privasi Anda sebagai pengguna website Adopt House. Sehubungan dengan layanan adopsi hewan yang kami sediakan, Anda dengan ini menyetujui bahwa alamat, alamat email, dan nomor telepon Anda akan kami kumpulkan dan simpan. Informasi pribadi ini akan kami gunakan secara eksklusif untuk memfasilitasi proses adopsi, yaitu dengan memberitahukan lokasi dan informasi kontak Anda kepada calon pengadopsi hewan yang Anda tawarkan. Dengan memberikan informasi ini, Anda memahami dan menyetujui bahwa informasi tersebut akan dibagikan kepada pihak ketiga yang berminat untuk mengadopsi hewan Anda.",
  description2: "Kami berkomitmen untuk menjaga keamanan data Anda sesuai dengan standar yang berlaku. Namun, perlu Anda pahami bahwa dalam konteks penggunaan informasi lokasi dan kontak Anda untuk keperluan adopsi hewan, potensi penyebaran data pribadi dapat terjadi di luar kendali langsung kami setelah informasi tersebut dibagikan kepada calon pengadopsi. Anda sepenuhnya bertanggung jawab atas konsekuensi yang mungkin timbul akibat penyebaran data pribadi Anda yang Anda berikan untuk keperluan adopsi hewan melalui platform kami, dan kami tidak bertanggung jawab atas kejadian penyebaran data tersebut setelah informasi dibagikan kepada pihak lain yang berkepentingan dalam proses adopsi.",
  description3: "Selain informasi kontak untuk keperluan adopsi, kami juga dapat mengumpulkan data mengenai preferensi hewan yang Anda sukai sebagai referensi. Data ini akan kami olah untuk memberikan rekomendasi hewan adopsi yang lebih sesuai dengan minat Anda di masa mendatang. Penggunaan data preferensi ini bertujuan untuk meningkatkan pengalaman Anda dalam menggunakan website kami dan membantu Anda menemukan hewan adopsi yang paling tepat.",
};
export const content2 = {
  title: "2.	Syarat & Ketentuan Tentang Postingan Hewan",
  description1: "Sebagai pengguna yang memposting informasi mengenai hewan di website Adopt House. Anda sepenuhnya bertanggung jawab atas konten yang Anda unggah. Anda diwajibkan untuk memberikan deskripsi yang jujur dan akurat mengenai hewan peliharaan Anda, termasuk informasi tentang kesehatan, kondisi fisik, riwayat, perilaku, dan aspek relevan lainnya sesuai dengan keadaan sebenarnya hewan tersebut. Informasi yang Anda berikan akan menjadi dasar bagi calon pengadopsi untuk membuat keputusan, oleh karena itu kejujuran dan transparansi sangat diharapkan. Anda juga menjamin bahwa Anda memiliki hak penuh untuk memposting informasi dan gambar hewan tersebut dan tidak melanggar hak kekayaan intelektual atau hak privasi pihak lain. Kami berhak untuk meninjau, memoderasi, atau menghapus postingan yang kami anggap tidak sesuai dengan standar dan tujuan website kami tanpa pemberitahuan sebelumnya, termasuk postingan yang terindikasi memberikan informasi yang tidak benar atau menyesatkan.",
  description2: "Kami memberlakukan kebijakan nol toleransi terhadap segala bentuk penyalahgunaan platform kami melalui postingan. Hal-hal seperti penyebaran iklan ilegal (misalnya, penjualan hewan langka dilindungi), penyisipan iklan yang tidak sah atau tanpa sepengetahuan kami dalam postingan adopsi, pengunggahan gambar atau konten yang tidak senonoh, serta penggunaan kata atau kalimat yang tidak pantas atau mengandung unsur ujaran kebencian sangat dilarang. Kami akan mengambil tindakan tegas terhadap pelanggaran semacam itu, termasuk penghapusan postingan, penangguhan atau pemblokiran akun pengguna yang bersangkutan, dan tidak menutup kemungkinan untuk melaporkan pelanggaran tersebut kepada pihak berwenang sesuai dengan hukum yang berlaku di Indonesia.",
  description3: "Tindakan tegas ini kami lakukan demi menjaga keamanan, kenyamanan, dan integritas platform kami bagi seluruh pengguna serta melindungi reputasi website Adopt House. Dengan memposting informasi hewan, Anda setuju untuk mematuhi syarat dan ketentuan ini serta memahami bahwa segala konsekuensi hukum yang timbul akibat pelanggaran sepenuhnya menjadi tanggung jawab Anda. Kami berhak untuk melakukan perubahan pada syarat dan ketentuan postingan ini sewaktu-waktu tanpa pemberitahuan sebelumnya.",
};
export const content3 = {
  title: "3.	Syarat & Ketentuan Tentang Adopsi",
  description1: "Adopt House berperan sebagai platform yang menghubungkan antara pemilik hewan yang ingin memberikan adopsi dengan calon pengadopsi. Perlu dipahami bahwa Adopt House tidak terlibat dalam proses transaksi finansial atau perjanjian adopsi secara langsung. Segala bentuk kesepakatan, negosiasi, dan transaksi yang terjadi di luar platform Adopt House, termasuk namun tidak terbatas pada biaya adopsi, persyaratan adopsi tambahan, atau serah terima hewan, sepenuhnya merupakan tanggung jawab dan kesepakatan antara pihak pemilik hewan dan calon pengadopsi. Adopt House tidak bertanggung jawab atas segala hal yang mungkin timbul akibat kesepakatan atau transaksi di luar platform kami.",
  description2: "Kami menghimbau kepada seluruh pengguna untuk melakukan verifikasi dan berhati-hati dalam berinteraksi dengan pihak lain. Calon pengadopsi disarankan untuk bertemu langsung dengan hewan yang akan diadopsi, memeriksa kondisi kesehatan dan riwayatnya, serta memahami sepenuhnya persyaratan yang diajukan oleh pemilik hewan. Pemilik hewan juga diharapkan untuk melakukan seleksi calon pengadopsi dengan bijak demi kesejahteraan hewan di masa depan. Adopt House tidak bertanggung jawab atas kualitas hewan yang diadopsi, perilaku hewan setelah adopsi, atau perselisihan yang mungkin timbul antara pemilik hewan sebelumnya dan pengadopsi setelah proses adopsi terjadi di luar platform kami.",
  description3: "Dengan menggunakan fitur adopsi di Adopt House, Anda memahami dan menyetujui bahwa peran kami terbatas pada penyediaan platform untuk menghubungkan pihak-pihak yang berkepentingan. Kami tidak memberikan jaminan atau garansi apapun terkait proses adopsi yang terjadi di luar platform ini. Pengguna bertanggung jawab penuh atas segala keputusan dan risiko yang terkait dengan adopsi hewan yang difasilitasi melalui website kami. Kami berhak untuk melakukan perubahan pada syarat dan ketentuan ini sewaktu-waktu demi keamanan dan kenyamanan seluruh pengguna Adopt House.",
};
export const content4 = {
  title: "4.	Syarat & Ketentuan Tentang Calon Pengadopsi",
  description1: "Sebagai calon pengadopsi yang menggunakan platform Adopt House, Anda menyatakan kesediaan penuh untuk bertanggung jawab atas segala kebutuhan hewan yang Anda adopsi. Ini mencakup penyediaan makanan yang layak, tempat tinggal yang aman dan nyaman, perawatan kesehatan yang memadai (termasuk vaksinasi dan pengobatan jika diperlukan), kasih sayang, serta perhatian yang berkelanjutan sesuai dengan kebutuhan spesies dan individu hewan yang Anda adopsi. Anda memahami bahwa mengadopsi hewan adalah komitmen jangka panjang yang memerlukan waktu, tenaga, dan sumber daya finansial.",
  description2: "Dengan mengajukan diri sebagai calon pengadopsi melalui Adopt House, Anda setuju untuk memberikan informasi yang benar dan lengkap mengenai diri Anda dan kemampuan Anda dalam merawat hewan. Informasi ini mungkin akan dibagikan kepada pemilik hewan yang Anda minati untuk diadopsi sebagai bagian dari proses seleksi. Kami menghimbau Anda untuk bersikap terbuka dan jujur dalam berkomunikasi dengan pemilik hewan mengenai pengalaman Anda sebelumnya dalam memelihara hewan, kondisi tempat tinggal Anda, serta rencana Anda untuk merawat hewan adopsi di masa depan.",
  description3: "Adopt House menyediakan platform untuk menghubungkan Anda dengan hewan yang membutuhkan rumah baru. Namun, keputusan akhir mengenai adopsi sepenuhnya berada di tangan pemilik hewan. Adopt House tidak dapat memberikan jaminan bahwa aplikasi adopsi Anda akan disetujui. Kami mendorong Anda untuk bersabar dan terus mencari hewan yang sesuai dengan kemampuan dan gaya hidup Anda. Dengan menggunakan platform ini, Anda menyadari bahwa Adopt House tidak bertanggung jawab atas perilaku atau kondisi kesehatan hewan setelah proses adopsi disetujui oleh pemilik hewan dan terjadi di luar platform kami.",
};
export const content5 = {
  title: "5.	Syarat & Ketentuan Tentang Lainnya",
  description1: "Untuk melengkapi syarat dan ketentuan yang telah disebutkan sebelumnya, terdapat beberapa poin tambahan yang penting untuk diperhatikan demi keamanan dan kenyamanan seluruh pengguna Adopt House serta perlindungan platform kami. Terkait penggunaan data, penting untuk menegaskan bahwa meskipun kami berupaya melindungi informasi pribadi pengguna, keamanan data secara absolut tidak dapat dijamin. Pengguna bertanggung jawab untuk menjaga kerahasiaan informasi akun mereka dan berhati-hati dalam membagikan informasi pribadi kepada pihak lain di luar platform yang tidak terverifikasi. Kami berhak untuk melakukan pemantauan aktivitas pengguna di platform untuk mendeteksi dan mencegah aktivitas yang mencurigakan atau melanggar ketentuan, dan data yang terkumpul dapat digunakan untuk tujuan tersebut serta untuk meningkatkan kualitas layanan kami.",
  description2: "Dalam hal perlindungan platform Adopt House, segala tindakan yang dapat mengganggu operasional website, seperti upaya peretasan, penyebaran virus atau malware, atau penggunaan bot secara berlebihan, sangat dilarang. Kami berhak untuk mengambil tindakan hukum yang sesuai terhadap pihak-pihak yang terbukti melakukan tindakan merugikan terhadap platform kami. Selain itu, kami berhak untuk mengubah, menangguhkan, atau menghentikan sebagian atau seluruh layanan Adopt House sewaktu-waktu tanpa pemberitahuan sebelumnya. Pengguna diharapkan untuk secara berkala meninjau syarat dan ketentuan ini untuk mengetahui adanya perubahan.",
  description3: "Terakhir, penting untuk dipahami bahwa Adopt House beroperasi sebagai platform perantara dan tidak bertanggung jawab atas interaksi atau kesepakatan yang terjadi antar pengguna di luar platform. Kami menghimbau seluruh pengguna untuk berkomunikasi dengan baik, saling menghormati, dan bertindak dengan itikad baik dalam setiap interaksi terkait adopsi hewan. Jika terjadi perselisihan antar pengguna, Adopt House tidak berkewajiban untuk terlibat dalam penyelesaian sengketa tersebut. Dengan menggunakan Adopt House, Anda menyetujui seluruh syarat dan ketentuan yang telah ditetapkan.",
};
